### ISSUE TITLE
fix dependency issues for python 3.13

### ISSUE THREAD

**Issue by rpm5099** [rpm5099/mfawesome#14]
mfawesome[all] fails on ultralytics dependency for 3.13 on qr libraries

**Comment by npereira89** [comment]
@rpm5099 Python 3.13 isn't supported by ultralytics yet. Downgrade to Python 3.12. or below.

**Comment by rpm5099** [comment]
@npereira89 I am the author of mfawesome so my goal was just to make the package work with 3.13.  For now I have transitioned  to using [opencv-contrib-python-headless](https://pypi.org/project/opencv-python-headless/) but thanks for the heads up!
